import csv
import os
import glob
import json


FEED_TAGS = [
    {"onestop_id":"f-9q8z-goldengateferry","tags":{"demo_feed": "true", "managed_by": "mtc-ca", "gtfs_data_exchange": "golden-gate-ferry"}},
    {"onestop_id":"f-soundtransit~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-9q9jy-unioncitytransit","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9qc-vinenapacounty","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-actransit~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-wsf~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-c0z4-bctransit~comoxvalleytransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-comox-valley-transit-system"}},
    {"onestop_id":"f-de30-ati","tags":{"status": "unreachable", "unstable_url": "true"}},
    {"onestop_id":"f-9q9-bart","tags":{"demo_feed": "true", "gtfs_data_exchange": "airbart"}},
    {"onestop_id":"f-c29p-bctransit~fraservalleyexpress","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-fraser-valley-express"}},
    {"onestop_id":"f-trimet~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-dr5r-mtanyctbusbrooklyn","tags":{"demo_feed": "true", "download_page_url": "http://web.mta.info/developers/download.html", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-dr5r-mtanyctbusmanhattan","tags":{"demo_feed": "true", "download_page_url": "http://web.mta.info/developers/download.html", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-dr5r-mtanyctbusstatenisland","tags":{"demo_feed": "true", "download_page_url": "http://web.mta.info/developers/download.html", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-dr72-mtanyctbusbronx","tags":{"demo_feed": "true", "download_page_url": "http://web.mta.info/developers/download.html", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-dr5x-mtanyctbusqueens","tags":{"demo_feed": "true", "download_page_url": "http://web.mta.info/developers/download.html", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-dr5r-mtabc","tags":{"demo_feed": "true", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-dr7-mtanyc~metro~north","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-dpe-therapid","tags":{"gtfs_data_exchange": "the-rapid"}},
    {"onestop_id":"f-dhw-browardcountytransit","tags":{"gtfs_data_exchange": "broward-county-transit"}},
    {"onestop_id":"f-7h2w-empresadetransportesetransitodebelohorizontes~a","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9whp-abqride","tags":{"gtfs_data_exchange": "abq-ride"}},
    {"onestop_id":"f-c3nf-calgarytransit","tags":{"gtfs_data_exchange": "calgary-transit"}},
    {"onestop_id":"f-c290-everetttransit","tags":{"gtfs_data_exchange": "everett-transit"}},
    {"onestop_id":"f-c38d-bctransit~princegeorgetransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-prince-george-transit-system"}},
    {"onestop_id":"f-c2b6v-bctransit~squamishtransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-squamish-transit-system"}},
    {"onestop_id":"f-9q8zmw-angelislandtiburonferry","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9qc14-americancanyontransit","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9q8zn-alcatrazhornblowerferry","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9qb-smart","tags":{"managed_by": "mtc-ca", "gtfs_data_exchange": "smart"}},
    {"onestop_id":"f-srhv-sgmspa","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-ezwg-transportsciutatcomtal","tags":{"unstable_url": "true", "gtfs_data_exchange": "transports-ciutat-comtal"}},
    {"onestop_id":"f-spz-cttnord","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-sr8-sienamobilità","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-spx-tiemmespa","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-dnr-piedmontauthorityforregionaltransportation","tags":{"gtfs_data_exchange": "piedmont-authority-for-regional-transportation"}},
    {"onestop_id":"f-dr5x-wwwnicebuscom","tags":{"demo_feed": "true", "unstable_url": "true", "gtfs_data_exchange": "nassau-inter-county-express"}},
    {"onestop_id":"f-c24-peopleforpeople","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-dr5-nj~transit~rail","tags":{"gtfs_data_exchange": "new-jersey-transit"}},
    {"onestop_id":"f-dr5r7-nycdotsiferry","tags":{"demo_feed": "true", "download_page_url": "http://www.nyc.gov/html/dot/html/about/datafeeds.shtml#ferry"}},
    {"onestop_id":"f-9q9-actransit","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-c23-soundtransit","tags":{"gtfs_data_exchange": "sound-transit"}},
    {"onestop_id":"f-9wh-riometroregionaltransitdistrict","tags":{"status": "unpublished"}},
    {"onestop_id":"f-intercitytransit~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-dr7cc-norwalktransit","tags":{"gtfs_data_exchange": "norwalk-transit"}},
    {"onestop_id":"f-c22e-intercitytransit","tags":{"gtfs_data_exchange": "intercity-transit"}},
    {"onestop_id":"f-c20-trimet","tags":{"feed_id": "TriMet", "gtfs_data_exchange": " Portland Aerial Tram"}},
    {"onestop_id":"f-dpz8-ttc","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-u0-switzerland","tags":{"manual_import": "true"}},
    {"onestop_id":"f-9rbm-albanytransit~or~us","tags":{"feed_id": "albanytransit-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9rb-benton~or~us","tags":{"feed_id": "benton-or-us", "managed_by": "trillium", "gtfs_data_exchange": "benton-county-transportation"}},
    {"onestop_id":"f-seattlestreetcar~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-c20f-bluestar~or~us","tags":{"feed_id": "bluestar-or-us", "managed_by": "trillium", "gtfs_data_exchange": "blue-star-bus"}},
    {"onestop_id":"f-c209-canbytransit~or~us","tags":{"feed_id": "canbytransit-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qcs-rosevilletransit","tags":{"gtfs_data_exchange": "roseville-transit"}},
    {"onestop_id":"f-c283-jamestownsklallam","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-c2qf-mountainline","tags":{"gtfs_data_exchange": "mountain-line"}},
    {"onestop_id":"f-9rb-caravan~or~us","tags":{"feed_id": "caravan-or-us", "managed_by": "trillium", "gtfs_data_exchange": "caravan-airport-transportation"}},
    {"onestop_id":"f-9rb-cascadespoint~or~us","tags":{"feed_id": "cascadespoint-or-us", "managed_by": "trillium", "gtfs_data_exchange": "cascades-point"}},
    {"onestop_id":"f-9rb-citytocityshuttle~or~us","tags":{"feed_id": "citytocityshuttle-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qh-omnitrans","tags":{"gtfs_data_exchange": "omnitrans"}},
    {"onestop_id":"f-9rc-eugenetobend~or~us","tags":{"feed_id": "eugenetobend-or-us", "managed_by": "trillium", "gtfs_data_exchange": "eugene-to-bend"}},
    {"onestop_id":"f-c21-hoodriver~or~us","tags":{"feed_id": "hoodriver-or-us", "managed_by": "trillium", "gtfs_data_exchange": "columbia-area-transit"}},
    {"onestop_id":"f-9ruf-mcacs~or~us","tags":{"feed_id": "mcacs-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c25v-milton~freewater~or~us","tags":{"feed_id": "milton-freewater-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c20-northwestpoint~or~us","tags":{"feed_id": "northwestpoint-or-us", "managed_by": "trillium", "gtfs_data_exchange": "northwest-point"}},
    {"onestop_id":"f-9rb-lanetransitdistrict","tags":{"gtfs_data_exchange": "lane-transit-district"}},
    {"onestop_id":"f-dpxr-oakvilletransit","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-c20d-rideconnection~or~us","tags":{"feed_id": "rideconnection-or-us", "managed_by": "trillium", "gtfs_data_exchange": "ride-connection"}},
    {"onestop_id":"f-drt0-metrowestregionaltransitauthority","tags":{"gtfs_data_exchange": "metrowest-regional-transit-authority"}},
    {"onestop_id":"f-drs-franklinregionaltransitauthority","tags":{"gtfs_data_exchange": "franklin-regional-transit-authority"}},
    {"onestop_id":"f-cttransithartford~rt","tags":{"notes": "Possibly blocking Amazon/EC2 address space."}},
    {"onestop_id":"f-9yzg-metrostlouis","tags":{"gtfs_data_exchange": "metro-st-louis"}},
    {"onestop_id":"f-9r2-southwestpoint~or~us","tags":{"feed_id": "southwestpoint-or-us", "managed_by": "trillium", "gtfs_data_exchange": "the-shuttle-inc"}},
    {"onestop_id":"f-9r8m-umpquatransit~or~us","tags":{"feed_id": "umpquatransit-or-us", "managed_by": "trillium", "gtfs_data_exchange": "u-trans"}},
    {"onestop_id":"f-9wgu-gunnisonvalleyrta","tags":{"managed_by": "mjc", "gtfs_data_exchange": "gunnison-valley-rta"}},
    {"onestop_id":"f-c28-jeffersontransitauthority","tags":{"managed_by": "mjc", "gtfs_data_exchange": "jefferson-transit-authority"}},
    {"onestop_id":"f-9r-easternpoint~or~us","tags":{"feed_id": "easternpoint-or-us", "managed_by": "trillium", "gtfs_data_exchange": "eastern-point"}},
    {"onestop_id":"f-calgarytransit~rt","tags":{"notes": "Not accessible."}},
    {"onestop_id":"f-9v6-capitalmetro","tags":{"gtfs_data_exchange": "capital-metro"}},
    {"onestop_id":"f-dp3-pace","tags":{"gtfs_data_exchange": "pace-suburban-bus-service"}},
    {"onestop_id":"f-dhx-palmtran","tags":{"manual_import": "true", "gtfs_data_exchange": "palm-tran"}},
    {"onestop_id":"f-kzf-nairobi~saccos","tags":{"schedule_frequencies": "true"}},
    {"onestop_id":"f-9g3-semovi","tags":{"schedule_frequencies": "true"}},
    {"onestop_id":"f-dr7-westchestercountybee~linesystem","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9qc-sanjoaquinrtd","tags":{"gtfs_data_exchange": "san-joaquin-regional-transit-district-rtd"}},
    {"onestop_id":"f-spn-trenitalia","tags":{"gtfs_data_exchange": "trenitalia"}},
    {"onestop_id":"f-dhv-sarasotacountyareatransit","tags":{"status": "unreachable", "gtfs_data_exchange": "sarasota-county-area-transit"}},
    {"onestop_id":"f-9vff-fortworthtransportationauthority","tags":{"gtfs_data_exchange": "fort-worth-transportation-authority"}},
    {"onestop_id":"f-9q8y-sfmta","tags":{"demo_feed": "true", "download_page_url": "https://www.sfmta.com/about-sfmta/reports/gtfs-transit-data", "gtfs_data_exchange": "san-francisco-municipal-transportation-agency"}},
    {"onestop_id":"f-drk-wwwshorelineeastcom","tags":{"gtfs_data_exchange": "shore-line-east"}},
    {"onestop_id":"f-srb-tperspa~ferrara","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-c3x1-stalberttransit","tags":{"gtfs_data_exchange": "st-albert-transit"}},
    {"onestop_id":"f-f25d-socitdetransportdemontral","tags":{"demo_feed": "true", "schedule_frequencies": "true"}},
    {"onestop_id":"f-9t9-suntran","tags":{"gtfs_data_exchange": "suntran"}},
    {"onestop_id":"f-dpwz-grandrivertransit","tags":{"gtfs_data_exchange": "grand-river-transit"}},
    {"onestop_id":"f-9q5b-longbeachtransit","tags":{"unstable_url": "true", "gtfs_data_exchange": "long-beach-transit"}},
    {"onestop_id":"f-c284-blackballferryline","tags":{"managed_by": "mjc", "gtfs_data_exchange": "black-ball-ferry-line"}},
    {"onestop_id":"f-9-amtrak~amtrakcalifornia~amtrakcharteredvehicle","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-tf34-metropolitantransportcorporation","tags":{"unstable_url": "true", "gtfs_data_exchange": "metropolitan-transport-corporation"}},
    {"onestop_id":"f-dp73-citilink","tags":{"status": "unpublished", "gtfs_data_exchange": "citilink"}},
    {"onestop_id":"f-9q60w-cityofsanluisobispotransit","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-dr5r-nyctsubway","tags":{"demo_feed": "true", "download_page_url": "http://web.mta.info/developers/download.html", "gtfs_data_exchange": "mta-new-york-city-transit"}},
    {"onestop_id":"f-9w-navajotransitsystem","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-9q9hu-cityofpaloaltoshuttle","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-dr5re-downtownalliance","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-9px-currypublictransit","tags":{"managed_by": "mjc", "gtfs_data_exchange": "curry-public-transit"}},
    {"onestop_id":"f-sr7-societatrasportiprovincialespa","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9qc2-trideltatransit","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-kingcountymetro~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-cbq6-duluthtransitauthority","tags":{"gtfs_data_exchange": "duluth-transit-authority"}},
    {"onestop_id":"f-c3x-edmontontransitsystem","tags":{"gtfs_data_exchange": "edmonton-transit-system"}},
    {"onestop_id":"f-9y69-embark","tags":{"gtfs_data_exchange": "embark"}},
    {"onestop_id":"f-dqcj-fairfaxconnector","tags":{"gtfs_data_exchange": "fairfax-connector"}},
    {"onestop_id":"f-sr7f-ferrotramviariaspa~ferroviedelnordbarese","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9qx5-suntran","tags":{"gtfs_data_exchange": "suntran"}},
    {"onestop_id":"f-9qh1-foothilltransit","tags":{"gtfs_data_exchange": "foothill-transit"}},
    {"onestop_id":"f-dp9-milwaukeecountytransitsystem","tags":{"gtfs_data_exchange": "milwaukee-county-transit-system"}},
    {"onestop_id":"f-9qbdx-santarosacitybus","tags":{"gtfs_data_exchange": "citybus"}},
    {"onestop_id":"f-ezty-metrobilbao","tags":{"gtfs_data_exchange": "metro-bilbao"}},
    {"onestop_id":"f-gc-arrivatrainswales~c2c~chilternrailways~crosscountry~eastcoa","tags":{"status": "unpublished", "unofficial": "true"}},
    {"onestop_id":"f-s0wz-socatur~taxisco","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-dhvrs-bullrunner","tags":{"schedule_frequencies": "true"}},
    {"onestop_id":"f-dr1b-harfordtransitlink","tags":{"gtfs_data_exchange": "harford-transit-link"}},
    {"onestop_id":"f-dr4-septa~rail","tags":{"demo_feed": "true", "gtfs_data_exchange": "septa"}},
    {"onestop_id":"f-dr4-septa~bus","tags":{"demo_feed": "true", "gtfs_data_exchange": "septa"}},
    {"onestop_id":"f-9tvbk-carlsbadmunicipaltransitsystem","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-wdw4-p2p","tags":{"feed_id": "P2P"}},
    {"onestop_id":"f-u-ruterbuss~ruterbåt~rutertrikk~rutertbane~buss~tog~båt~flytog","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-c23n-microsoftshuttles","tags":{"source": "unofficial"}},
    {"onestop_id":"f-9q5-metro~losangeles","tags":{"demo_feed": "true", "gtfs_data_exchange": "la-metro"}},
    {"onestop_id":"f-9q5-metro~losangeles~rail","tags":{"feed_id": "us_ca_lacmta_rail", "demo_feed": "true", "manual_import": "true", "gtfs_data_exchange": "la-metro"}},
    {"onestop_id":"f-9q5f-glendalebeeline","tags":{"gtfs_data_exchange": "glendale-beeline"}},
    {"onestop_id":"f-dhv-hillsborougharearegionaltransit","tags":{"gtfs_data_exchange": "hillsborough-area-regional-transit"}},
    {"onestop_id":"f-9qb-goldengatetransit","tags":{"demo_feed": "true", "gtfs_data_exchange": "golden-gate-transit"}},
    {"onestop_id":"f-dr63-monroecountytransitauthority","tags":{"gtfs_data_exchange": "monroe-county-transit-authority"}},
    {"onestop_id":"f-dpxj-hamiltonstreetrailway","tags":{"gtfs_data_exchange": "hamilton-street-railway"}},
    {"onestop_id":"f-dq9-hrt","tags":{"gtfs_data_exchange": "hampton-roads-transit-hrt"}},
    {"onestop_id":"f-c0r-pacifictransit","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-dpz-gotransit","tags":{"demo_feed": "true", "gtfs_data_exchange": "go-transit"}},
    {"onestop_id":"f-c28-clallamtransitsystem","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-c25y-valleytransit","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-c28-islandtransit","tags":{"status": "unpublished", "gtfs_data_exchange": "island-transit"}},
    {"onestop_id":"f-u-nl","tags":{"feed_id": "NL", "manual_import": "true"}},
    {"onestop_id":"f-dqct-annapolistransit","tags":{"gtfs_data_exchange": "annapolis-transit"}},
    {"onestop_id":"f-dpwz-guelphtransit","tags":{"manual_import": "true", "gtfs_data_exchange": "guelph-transit"}},
    {"onestop_id":"f-dnzft-hdpt","tags":{"gtfs_data_exchange": "harrisonburg-department-of-public-transportation"}},
    {"onestop_id":"f-dp4d-indygo","tags":{"gtfs_data_exchange": "indygo"}},
    {"onestop_id":"f-u905-lublin","tags":{"status": "unreachable"}},
    {"onestop_id":"f-9qce-sacramentoregionaltransit","tags":{"gtfs_data_exchange": "sacramento-regional-transit"}},
    {"onestop_id":"f-dnh-marta","tags":{"demo_feed": "true", "unstable_url": "true", "gtfs_data_exchange": "metropolitan-atlanta-rapid-transit-authority"}},
    {"onestop_id":"f-bfpu-theride","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-w21z-lta","tags":{"managed_by": "Buuuk", "unofficial": "true"}},
    {"onestop_id":"f-eysb-empresamalagueñadetransportes","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9q9-modesto~ca~us","tags":{"feed_id": "modesto-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "modesto-area-express"}},
    {"onestop_id":"f-dpe0-kalamazoometrotransit","tags":{"status": "unpublished"}},
    {"onestop_id":"f-9q5-ladot","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-dn4m-huntsvilleshuttle","tags":{"gtfs_data_exchange": "huntsville-shuttle"}},
    {"onestop_id":"f-9qbb-marintransit","tags":{"demo_feed": "true", "gtfs_data_exchange": "marin-transit"}},
    {"onestop_id":"f-drt3-909983","tags":{"feed_id": "909_983"}},
    {"onestop_id":"f-djfq-birminghamjeffersoncountytransitauthority","tags":{"gtfs_data_exchange": "birmingham-jefferson-county-transit-authority"}},
    {"onestop_id":"f-gc6y-horanscoaches","tags":{"status": "outdated"}},
    {"onestop_id":"f-drt-mbta","tags":{"demo_feed": "true", "schedule_frequencies": "true"}},
    {"onestop_id":"f-gceh9-leonardcoaches","tags":{"status": "outdated"}},
    {"onestop_id":"f-gc1y3-paradisecoaches","tags":{"status": "outdated"}},
    {"onestop_id":"f-gc7j-southkildarecommunitytransport","tags":{"status": "outdated"}},
    {"onestop_id":"f-gc-aircoach","tags":{"gtfs_data_exchange": "aircoach"}},
    {"onestop_id":"f-metra~rt","tags":{"notes": "Needs HTTP Basic Auth."}},
    {"onestop_id":"f-u2f-dpp","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-dpz2-miway","tags":{"gtfs_data_exchange": "miway"}},
    {"onestop_id":"f-9qf-laketahoe~ca~us","tags":{"feed_id": "laketahoe-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9q8zr-tidelinewatertaxi~ca~us","tags":{"feed_id": "tidelinewatertaxi-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c263-selah~wa~us","tags":{"feed_id": "selah-wa-us"}},
    {"onestop_id":"f-drvc-rtp~me~us","tags":{"feed_id": "rtp-me-us"}},
    {"onestop_id":"f-dr5r-path~nj~us","tags":{"feed_id": "path-nj-us", "demo_feed": "true", "managed_by": "trillium", "download_page_url": "http://www.panynj.gov/path/developers.html", "gtfs_data_exchange": "path"}},
    {"onestop_id":"f-9pp-humboldtcounty~ca~us","tags":{"feed_id": "humboldtcounty-ca-us", "managed_by": "trillium", "gtfs_data_exchange": " Arcata & Mad River Transit System"}},
    {"onestop_id":"f-9qd-yosemite~ca~us","tags":{"feed_id": "yosemite-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-drg-addisoncounty~vt~us","tags":{"feed_id": "addisoncounty-vt-us", "managed_by": "trillium", "gtfs_data_exchange": "addison-county-transit-resources"}},
    {"onestop_id":"f-9qf-amador~ca~us","tags":{"feed_id": "amador-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "amador-transit"}},
    {"onestop_id":"f-drt-baystatecruisecompany~ma~us","tags":{"feed_id": "baystatecruisecompany-ma-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "bay-state-cruise-company"}},
    {"onestop_id":"f-9qhc-beaumont~ca~us","tags":{"feed_id": "beaumont-ca-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "beaumont-pass-transit"}},
    {"onestop_id":"f-dp89-beloittransit~wi~us","tags":{"feed_id": "beloittransit-wi-us", "managed_by": "trillium", "gtfs_data_exchange": "beloit-transit-system"}},
    {"onestop_id":"f-dre-berkshire~ma~us","tags":{"feed_id": "berkshire-ma-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qhf-bigbear~ca~us","tags":{"feed_id": "bigbear-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "mountain-transit"}},
    {"onestop_id":"f-drmr-brockton~ma~us","tags":{"feed_id": "brockton-ma-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "brockton-area-transit-authority"}},
    {"onestop_id":"f-9qnx-bullheadareatransit~az~us","tags":{"feed_id": "bullheadareatransit-az-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9x-bustang~co~us","tags":{"feed_id": "bustang-co-us", "managed_by": "trillium", "gtfs_data_exchange": "bustang"}},
    {"onestop_id":"f-c2pvx-butte~mt~us","tags":{"feed_id": "butte-mt-us", "managed_by": "trillium", "gtfs_data_exchange": "butte-silver-bow"}},
    {"onestop_id":"f-9qf-calaveras~ca~us","tags":{"feed_id": "calaveras-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "calaveras-transit"}},
    {"onestop_id":"f-drtd-capeann~ma~us","tags":{"feed_id": "capeann-ma-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "cape-ann-transportation-authority"}},
    {"onestop_id":"f-dq25-capital~area~transit~nc~us","tags":{"feed_id": "capital-area-transit-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dnrg-cary~transit~nc~us","tags":{"feed_id": "cary-transit-nc-us", "managed_by": "trillium", "gtfs_data_exchange": "cary-transit"}},
    {"onestop_id":"f-dnru-chapel~hill~transit~nc~us","tags":{"feed_id": "chapel-hill-transit-nc-us", "managed_by": "trillium", "gtfs_data_exchange": "chapel-hill-transit"}},
    {"onestop_id":"f-dnjj-clemson~sc~us","tags":{"feed_id": "clemson-sc-us", "managed_by": "trillium", "gtfs_data_exchange": "clemson-area-transit", "schedule_frequencies": "true"}},
    {"onestop_id":"f-9qh2s-corona~ca~us","tags":{"feed_id": "corona-ca-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "corona-cruiser"}},
    {"onestop_id":"f-9w0md-cottonwood~az~us","tags":{"feed_id": "cottonwood-az-us", "managed_by": "trillium", "gtfs_data_exchange": "cottonwood-area-transit"}},
    {"onestop_id":"f-drs-crtransit~vt~us","tags":{"feed_id": "crtransit-vt-us", "managed_by": "trillium", "gtfs_data_exchange": "the-current"}},
    {"onestop_id":"f-drms-cuttyhunkferryco~ma~us","tags":{"feed_id": "cuttyhunkferryco-ma-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9pr-delnorte~ca~us","tags":{"feed_id": "delnorte-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "redwood-coast-transit"}},
    {"onestop_id":"f-dnru-durham~area~transit~authority~nc~us","tags":{"feed_id": "durham-area-transit-authority-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-drsh-dvtamoover~vt~us","tags":{"feed_id": "dvtamoover-vt-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9q-easternsierra~ca~us","tags":{"feed_id": "easternsierra-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "eastern-sierra-transit-authority"}},
    {"onestop_id":"f-9qc-eldoradotransit~ca~us","tags":{"feed_id": "eldoradotransit-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "el-dorado-transit"}},
    {"onestop_id":"f-9q9y-escalon~ca~us","tags":{"feed_id": "escalon-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qc-fairfield~ca~us","tags":{"feed_id": "fairfield-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "fairfield-and-suisun-transit"}},
    {"onestop_id":"f-drq-freedomcruiseline~ma~us","tags":{"feed_id": "freedomcruiseline-ma-us", "managed_by": "trillium", "gtfs_data_exchange": "freedom-cruise-line"}},
    {"onestop_id":"f-9qd-fresnocounty~ca~us","tags":{"feed_id": "fresnocounty-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "fresno-county-rural-transit-agency"}},
    {"onestop_id":"f-dre-greenmtncn~vt~us","tags":{"feed_id": "greenmtncn-vt-us", "managed_by": "trillium", "gtfs_data_exchange": "o-dre-greenmountaincommunitynetworkinc"}},
    {"onestop_id":"f-drq5-hylinecruises~ma~us","tags":{"feed_id": "hylinecruises-ma-us", "managed_by": "trillium", "gtfs_data_exchange": "hy-line-cruises"}},
    {"onestop_id":"f-9yz-jeffersoncounty~mo~us","tags":{"feed_id": "jeffersoncounty-mo-us", "managed_by": "trillium", "gtfs_data_exchange": "jeffco-express"}},
    {"onestop_id":"f-9q7-kerncounty~ca~us","tags":{"feed_id": "kerncounty-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "kern-regional-transit"}},
    {"onestop_id":"f-9muq-lagunabeach~ca~us","tags":{"feed_id": "lagunabeach-ca-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "laguna-beach-transit"}},
    {"onestop_id":"f-9qb-laketransit~ca~us","tags":{"feed_id": "laketransit-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "lake-transit"}},
    {"onestop_id":"f-c26-linktransit~wa~us","tags":{"feed_id": "linktransit-wa-us", "managed_by": "trillium", "gtfs_data_exchange": "link-transit"}},
    {"onestop_id":"f-9qb-mendocino~ca~us","tags":{"feed_id": "mendocino-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "mendocino-transit-authority"}},
    {"onestop_id":"f-9qd-mercedthebus~ca~us","tags":{"feed_id": "mercedthebus-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "the-bus"}},
    {"onestop_id":"f-drt7-merrimackvalley~ma~us","tags":{"feed_id": "merrimackvalley-ma-us", "managed_by": "trillium", "gtfs_data_exchange": "merrimack-valley-regional-transit-authority"}},
    {"onestop_id":"f-drsf-montachusett~ma~us","tags":{"feed_id": "montachusett-ma-us", "managed_by": "trillium", "gtfs_data_exchange": "montachusett-regional-transit-authority"}},
    {"onestop_id":"f-djf8-montgomerytransit~al~us","tags":{"feed_id": "montgomerytransit-al-us", "managed_by": "trillium", "gtfs_data_exchange": "montgomery-transit"}},
    {"onestop_id":"f-dq259-ncsu~wolfline~nc~us","tags":{"feed_id": "ncsu-wolfline-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9myr-paloverdevalley~ca~us","tags":{"feed_id": "paloverde_valley-ca-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "palo-verde-valley-transit-agency"}},
    {"onestop_id":"f-9qbc9-petalumatransit~petaluma~ca~us","tags":{"feed_id": "petalumatransit-petaluma-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9q5b4-pvpta~ca~us","tags":{"feed_id": "pvpta-ca-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "palos-verdes-peninsula-transit-authority"}},
    {"onestop_id":"f-9we1-redappletransit~nm~us","tags":{"feed_id": "redappletransit-nm-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c20w-rivercitiestransit~wa~us","tags":{"feed_id": "rivercitiestransit-wa-us", "managed_by": "trillium", "gtfs_data_exchange": "rivercities-transit"}},
    {"onestop_id":"f-dru-ruralcommunity~vt~us","tags":{"feed_id": "ruralcommunity-vt-us", "managed_by": "trillium", "gtfs_data_exchange": "rural-community-transportation"}},
    {"onestop_id":"f-9q99-sanbenito~ca~us","tags":{"feed_id": "sanbenito-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "san-benito-county-express"}},
    {"onestop_id":"f-9zep-siouxareametro~sd~us","tags":{"feed_id": "siouxareametro-sd-us", "managed_by": "trillium", "gtfs_data_exchange": "sioux-area-metro"}},
    {"onestop_id":"f-9r2-siskiyou~ca~us","tags":{"feed_id": "siskiyou-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "siskiyou-transit-and-general-express"}},
    {"onestop_id":"f-9qc0-soltrans~ca~us","tags":{"feed_id": "soltrans-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "soltrans"}},
    {"onestop_id":"f-9qb-sonomacounty~ca~us","tags":{"feed_id": "sonomacounty-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "cloverdale-transit"}},
    {"onestop_id":"f-djn-spacecoast~fl~us","tags":{"feed_id": "spacecoast-fl-us", "managed_by": "trillium", "gtfs_data_exchange": "space-coast-area-transit"}},
    {"onestop_id":"f-dru-stagecoach~vt~us","tags":{"feed_id": "stagecoach-vt-us", "managed_by": "trillium", "gtfs_data_exchange": "stagecoach-transportation-services"}},
    {"onestop_id":"f-9qd-stanislaus~ca~us","tags":{"feed_id": "stanislaus-ca-us", "managed_by": "trillium", "gtfs_data_exchange": " Ceres Area Transit"}},
    {"onestop_id":"f-dpeg-capitalareatransportationauthority","tags":{"gtfs_data_exchange": "capital-area-transportation-authority"}},
    {"onestop_id":"f-dpz-durhamregiontransit","tags":{"gtfs_data_exchange": "durham-region-transit"}},
    {"onestop_id":"f-c22y-kitsaptransit","tags":{"gtfs_data_exchange": "kitsap-transit"}},
    {"onestop_id":"f-c2h-northeast~or~us","tags":{"feed_id": "northeast-or-us", "managed_by": "trillium", "gtfs_data_exchange": "Northeast Oregon Public Transit"}},
    {"onestop_id":"f-9pzdp-rhodyexpress~or~us","tags":{"feed_id": "rhodyexpress-or-us", "managed_by": "trillium", "gtfs_data_exchange": "rhody-express"}},
    {"onestop_id":"f-c815-streamlinetransit~mt~us","tags":{"feed_id": "streamlinetransit-mt-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c29p-bctransit~centralfraservalleytransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-central-fraser-valley-transit-system"}},
    {"onestop_id":"f-c29r-bctransit~chilliwacktransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-chilliwack-transit-system"}},
    {"onestop_id":"f-9w0q-verdelynx~az~us","tags":{"feed_id": "verdelynx-az-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qh-victorville~ca~us","tags":{"feed_id": "victorville-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c342-bctransit~kamloopstransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-kamloops-transit-system"}},
    {"onestop_id":"f-c2g5-bctransit~kelownaregionaltransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-kelowna-regional-transit-system"}},
    {"onestop_id":"f-c0z-bctransit~rdntransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-rdn-transit-system"}},
    {"onestop_id":"f-9rb3p-southlanewheels~or~us","tags":{"feed_id": "southlanewheels-or-us", "managed_by": "trillium", "gtfs_data_exchange": "south-lane-wheels"}},
    {"onestop_id":"f-c2b1-bctransit~sunshinecoasttransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-sunshine-coast-transit-system"}},
    {"onestop_id":"f-c28-bctransit~victoriaregionaltransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-victoria-regional-transit-system"}},
    {"onestop_id":"f-c2bt-bctransit~whistlertransitsystem","tags":{"demo_feed": "true", "gtfs_data_exchange": "bc-transit-whistler-transit-system"}},
    {"onestop_id":"f-drm-vineyardfastferry~ri~us","tags":{"feed_id": "vineyardfastferry-ri-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dru-vttranslines~vt~us","tags":{"feed_id": "vttranslines-vt-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dp9k-waukeshacounty~wi~us","tags":{"feed_id": "waukeshacounty-wi-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qc-westcat~ca~us","tags":{"feed_id": "westcat-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9q8zm-blue~goldfleet","tags":{"managed_by": "mtc-ca", "gtfs_data_exchange": "blue-gold-fleet"}},
    {"onestop_id":"f-dpz2-bramptontransit","tags":{"gtfs_data_exchange": "brampton-transit"}},
    {"onestop_id":"f-9q9-acealtamontcorridorexpress","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9q9j-dumbartonexpress","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-c20-wilsonville~or~us","tags":{"feed_id": "wilsonville-or-us", "managed_by": "trillium", "gtfs_data_exchange": "smart"}},
    {"onestop_id":"f-c20g-c~tran","tags":{"gtfs_data_exchange": "c-tran"}},
    {"onestop_id":"f-dre-cdta","tags":{"gtfs_data_exchange": "cdta"}},
    {"onestop_id":"f-9rb-cherriots","tags":{"gtfs_data_exchange": "cherriots"}},
    {"onestop_id":"f-dr5-mtanyclirr","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-9qc-yubasutter~ca~us","tags":{"feed_id": "yubasutter-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qc60-vacavillecitycoach","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9zmk-desmoinesarearegionaltransitauthority","tags":{"gtfs_data_exchange": "des-moines-area-regional-transit-authority"}},
    {"onestop_id":"f-dnr-tta~regionalbus~nc~us","tags":{"feed_id": "tta-regionalbus-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-u0n5w-malpensa~shuttle","tags":{"status": "unreachable", "unstable_url": "true"}},
    {"onestop_id":"f-9q56-thousandoaks~ca~us","tags":{"feed_id": "thousandoaks-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "thousand-oaks-transit"}},
    {"onestop_id":"f-djj6-thehernandoexpress~fl~us","tags":{"status": "outdated", "feed_id": "thehernandoexpress-fl-us"}},
    {"onestop_id":"f-djjk-citruscounty~fl~us","tags":{"feed_id": "citruscounty-fl-us"}},
    {"onestop_id":"f-dj3-ecat~fl~us","tags":{"feed_id": "ecat-fl-us", "managed_by": "trillium", "gtfs_data_exchange": "escambia-county-area-transit"}},
    {"onestop_id":"f-dj6m-okaloosacountytransit~fl~us","tags":{"status": "outdated", "feed_id": "okaloosacountytransit-fl-us", "gtfs_data_exchange": "emerald-coast-rider"}},
    {"onestop_id":"f-s-anm~it","tags":{"manual_import": "true", "schedule_frequencies": "true"}},
    {"onestop_id":"f-f08e-thunderbaytransit","tags":{"gtfs_data_exchange": "thunder-bay-transit"}},
    {"onestop_id":"f-u-se","tags":{"feed_id": "SE"}},
    {"onestop_id":"f-dr5-nj~transit~bus","tags":{"gtfs_data_exchange": "new-jersey-transit"}},
    {"onestop_id":"f-dpsc-detroitdepartmentoftransportation","tags":{"gtfs_data_exchange": "detroit-department-of-transportation"}},
    {"onestop_id":"f-9r-peoplemover~or~us","tags":{"feed_id": "peoplemover-or-us", "managed_by": "trillium", "gtfs_data_exchange": "people-mover"}},
    {"onestop_id":"f-dj75-baytowntrolley~fl~us","tags":{"feed_id": "baytowntrolley-fl-us", "managed_by": "trillium", "gtfs_data_exchange": "bay-town-trolley"}},
    {"onestop_id":"f-c20fb-ceic~or~us","tags":{"feed_id": "ceic-or-us"}},
    {"onestop_id":"f-9ydy-wichitatransit","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-drmg-marthasvineyard~ma~us","tags":{"feed_id": "marthasvineyard-ma-us"}},
    {"onestop_id":"f-dpsb-transitwindsor","tags":{"gtfs_data_exchange": "transit-windsor"}},
    {"onestop_id":"f-9wvk-mountainmetropolitantransit","tags":{"status": "unreachable", "gtfs_data_exchange": "mountain-metropolitan-transit"}},
    {"onestop_id":"f-drkhr-cttransit~meriden","tags":{"status": "removed"}},
    {"onestop_id":"f-dphg-centralohiotransitauthority","tags":{"gtfs_data_exchange": "central-ohio-transit-authority"}},
    {"onestop_id":"f-drm-thegreaterattleborotauntonregionaltransitauthority","tags":{"managed_by": "trillium"}},
    {"onestop_id":"f-drq-capecodregionaltransitauthorityccrta","tags":{"managed_by": "trillium", "gtfs_data_exchange": "cape-cod-regional-transit-authority"}},
    {"onestop_id":"f-9vg-dallasarearapidtransit","tags":{"gtfs_data_exchange": "dallas-area-rapid-transit"}},
    {"onestop_id":"f-dnfq-bloomingtontransit","tags":{"gtfs_data_exchange": "bloomington-transit"}},
    {"onestop_id":"f-gbqu-semitan","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-u4k-kolumbus","tags":{"gtfs_data_exchange": "kolumbus"}},
    {"onestop_id":"f-drq4-thewave~nantucketregionaltransitauthority","tags":{"managed_by": "trillium"}},
    {"onestop_id":"f-u-flixbus","tags":{"manual_import": "true"}},
    {"onestop_id":"f-drt6-lowellregionaltransitauthority","tags":{"managed_by": "trillium", "gtfs_data_exchange": "lowell-regional-transit-authority"}},
    {"onestop_id":"f-9ry8-mountainridestransportationauthoritymrta","tags":{"gtfs_data_exchange": "mountain-rides-transportation-authority-mrta"}},
    {"onestop_id":"f-c427-cityandboroughofjuneau~ak~us","tags":{"feed_id": "cityandboroughofjuneau-ak-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dnwe-radford~va~us","tags":{"feed_id": "radford-va-us", "gtfs_data_exchange": "radford-transit"}},
    {"onestop_id":"f-djm2-regionaltransitsystem","tags":{"gtfs_data_exchange": "regional-transit-system"}},
    {"onestop_id":"f-f25f-rseaudetransportdelongueuil","tags":{"gtfs_data_exchange": "rseau-de-transport-de-longueuil"}},
    {"onestop_id":"f-rb6b-metrochristchurch","tags":{"gtfs_data_exchange": "metro-christchurch"}},
    {"onestop_id":"f-dnwe-pulaski~va~us","tags":{"feed_id": "pulaski-va-us", "gtfs_data_exchange": "pulaski-area-transit"}},
    {"onestop_id":"f-dn5bpr-atlanticstationshuttle","tags":{"gtfs_data_exchange": "atlantic-station-shuttle"}},
    {"onestop_id":"f-djz4-carta~sc~us","tags":{"feed_id": "carta-sc-us", "managed_by": "trillium", "gtfs_data_exchange": "charleston-area-regional-transportation-authority"}},
    {"onestop_id":"f-u20-trenitalia~obb","tags":{"gtfs_data_exchange": "trenitalia"}},
    {"onestop_id":"f-dxfy-halifaxtransit~hrm","tags":{"gtfs_data_exchange": "halifax-transit"}},
    {"onestop_id":"f-9q4-smat~ca~us","tags":{"feed_id": "smat-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dpzk-barrietransit","tags":{"gtfs_data_exchange": "barrie-transit"}},
    {"onestop_id":"f-translink~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-djjt-suntran~fl~us","tags":{"feed_id": "suntran-fl-us", "gtfs_data_exchange": "suntran"}},
    {"onestop_id":"f-c214-sandy~or~us","tags":{"feed_id": "sandy-or-us", "managed_by": "trillium", "gtfs_data_exchange": "o-c214-sandyareametro"}},
    {"onestop_id":"f-9vk-metropolitantransitauthorityofharriscounty","tags":{"gtfs_data_exchange": "metropolitan-transit-authority-of-harris-county"}},
    {"onestop_id":"f-9xh-ecotransit~co~us","tags":{"feed_id": "ecotransit-co-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9r4-rtcride","tags":{"gtfs_data_exchange": "rtc-ride"}},
    {"onestop_id":"f-9q9p3-emerygoround","tags":{"feed_id": "emerygoround-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9q9hy-mountainview","tags":{"feed_id": "mountainview-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dnq9-ckrider~nc~us","tags":{"feed_id": "ckrider-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9qh45-duartetransit~ca~us","tags":{"feed_id": "duartetransit-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dps-michiganflyer~mi~us","tags":{"feed_id": "michiganflyer-mi-us", "managed_by": "trillium"}},
    {"onestop_id":"f-drt8-nps~boha~ferries","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-9q5cx-montereypark~ca~us","tags":{"feed_id": "montereypark-ca-us", "managed_by": "trillium"}},
    {"onestop_id":"f-drke-ninetown~connecticut~us","tags":{"feed_id": "ninetown-connecticut-us", "managed_by": "trillium"}},
    {"onestop_id":"f-f85p5-t3transit","tags":{"status": "unpublished"}},
    {"onestop_id":"f-dq9k-wata","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-drt3-123bc~ma~us","tags":{"feed_id": "123bc-ma-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dq2s-tarriver~nc~us","tags":{"feed_id": "tarriver-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9q5-airportvaletexpress~ca~us","tags":{"feed_id": "airportvaletexpress-ca-us"}},
    {"onestop_id":"f-9xj5sg-universitycoloradoboulder~co~us","tags":{"feed_id": "universitycoloradoboulder-co-us"}},
    {"onestop_id":"f-bdvk-anchoragepeoplemover","tags":{"gtfs_data_exchange": "anchorage-people-mover"}},
    {"onestop_id":"f-c1f-interisland~ak~us","tags":{"feed_id": "interisland-ak-us"}},
    {"onestop_id":"f-9zq4g-762","tags":{"feed_id": "762"}},
    {"onestop_id":"f-drt0-limoliner~ma~us","tags":{"feed_id": "limoliner-ma-us"}},
    {"onestop_id":"f-drm-plymouthbrockton~ma~us","tags":{"feed_id": "plymouthbrockton-ma-us"}},
    {"onestop_id":"f-dng1-transitauthorityofrivercity","tags":{"gtfs_data_exchange": "transit-authority-of-river-city"}},
    {"onestop_id":"f-djmu-jacksonvilletransportationauthority","tags":{"gtfs_data_exchange": "jacksonville-transportation-authority"}},
    {"onestop_id":"f-c2kx-spokanetransitauthority","tags":{"gtfs_data_exchange": "spokane-transit-authority"}},
    {"onestop_id":"f-9mu-northcountytransitdistrict","tags":{"gtfs_data_exchange": "north-county-transit-district"}},
    {"onestop_id":"f-u4x-rb","tags":{"feed_id": "RB"}},
    {"onestop_id":"f-dnn3-thecomet~sc~us","tags":{"feed_id": "thecomet-sc-us"}},
    {"onestop_id":"f-dppn-portauthorityofalleghenycounty","tags":{"gtfs_data_exchange": "port-authority-of-allegheny-county"}},
    {"onestop_id":"f-9q6-kcapta~ca~us","tags":{"feed_id": "kcapta-ca-us"}},
    {"onestop_id":"f-dngb-lextran","tags":{"gtfs_data_exchange": "lanta"}},
    {"onestop_id":"f-9zqv-coralvilletransitsystem~ia~us","tags":{"feed_id": "coralvilletransitsystem-ia-us"}},
    {"onestop_id":"f-u1-delijn","tags":{"gtfs_data_exchange": "de-lijn"}},
    {"onestop_id":"f-dps2w-universityofmichigantransitservices","tags":{"gtfs_data_exchange": "university-of-michigan-transit-services"}},
    {"onestop_id":"f-9ynm-centralarkansastransitauthority","tags":{"status": "unpublished"}},
    {"onestop_id":"f-dhm-keywest~fl~us","tags":{"feed_id": "keywest-fl-us"}},
    {"onestop_id":"f-c20ep-swanisland~or~us","tags":{"feed_id": "swanisland-or-us", "managed_by": "trillium", "gtfs_data_exchange": "swan-island-tma"}},
    {"onestop_id":"f-drm-rhodeislandpublictransitauthority","tags":{"gtfs_data_exchange": "ripta"}},
    {"onestop_id":"f-9zqvh-cambus~ia~us","tags":{"feed_id": "cambus-ia-us"}},
    {"onestop_id":"f-c0-bcferries~bc~ca","tags":{"feed_id": "bcferries-bc-ca"}},
    {"onestop_id":"f-drt3-middlesex~ma~us","tags":{"feed_id": "middlesex-ma-us"}},
    {"onestop_id":"f-dp3-metra","tags":{"gtfs_data_exchange": "metra"}},
    {"onestop_id":"f-9q6-sanluisobisporegionaltransitauthority~pasoroblesexpress~so","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-9q611-morrobaytransit","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-9qh-metrolinktrains","tags":{"gtfs_data_exchange": "metrolink"}},
    {"onestop_id":"f-dp-945963","tags":{"feed_id": "945_963"}},
    {"onestop_id":"f-c28-pugetsoundexpress","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-9w-arizonashuttle~az~us","tags":{"feed_id": "arizonashuttle-az-us"}},
    {"onestop_id":"f-9qb-airportexpressinc~ca~us","tags":{"feed_id": "airportexpressinc-ca-us"}},
    {"onestop_id":"f-9qdc-clovistransit~ca~us","tags":{"feed_id": "clovistransit-ca-us"}},
    {"onestop_id":"f-c22-graysharbortransit","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-9q5bf-lawndale~ca~us","tags":{"feed_id": "lawndale-ca-us"}},
    {"onestop_id":"f-9q9-monterey~salinastransit","tags":{"gtfs_data_exchange": "monterey-salinas-transit"}},
    {"onestop_id":"f-9qqj-rtcsnv","tags":{"gtfs_data_exchange": "regional-transportation-commission-of-southern-nevada"}},
    {"onestop_id":"f-dqcqz-bwithurgoodmarshallairport","tags":{"gtfs_data_exchange": "bwi-thurgood-marshall-airport"}},
    {"onestop_id":"f-dr41-ceciltransit","tags":{"gtfs_data_exchange": "cecil-transit"}},
    {"onestop_id":"f-dqcx8-charmcitycirculator","tags":{"gtfs_data_exchange": "charm-city-circulator"}},
    {"onestop_id":"f-f81y-codiactranspo","tags":{"gtfs_data_exchange": "codiac-transpo"}},
    {"onestop_id":"f-dqc-montgomerycountymdrideon","tags":{"gtfs_data_exchange": "montgomery-county-md-ride-on"}},
    {"onestop_id":"f-c28-nstranslinkca","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-ezjm-empresamunicipaldetransportes","tags":{"gtfs_data_exchange": "madrid"}},
    {"onestop_id":"f-9q5b-torrancetransit","tags":{"demo_feed": "true", "gtfs_data_exchange": "torrance-transit"}},
    {"onestop_id":"f-dp3-cta","tags":{"gtfs_data_exchange": "chicago-transit-authority"}},
    {"onestop_id":"f-dp8m-metrotransit~cityofmadison","tags":{"gtfs_data_exchange": "metro-transit"}},
    {"onestop_id":"f-9rc-cascadeseast~or~us","tags":{"feed_id": "cascadeseast-or-us", "managed_by": "trillium", "gtfs_data_exchange": "cascades-east-transit"}},
    {"onestop_id":"f-9r9-craterlaketrolley~or~us","tags":{"feed_id": "craterlaketrolley-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9rb-diamondexpress~or~us","tags":{"feed_id": "diamondexpress-or-us", "managed_by": "trillium", "gtfs_data_exchange": "diamond-express"}},
    {"onestop_id":"f-9rbs-linnshuttle~or~us","tags":{"feed_id": "linnshuttle-or-us", "managed_by": "trillium", "gtfs_data_exchange": "linn-shuttle"}},
    {"onestop_id":"f-dqcq-regionaltransportationagencyofcentralmaryland","tags":{"gtfs_data_exchange": "regional-transportation-agency-of-central-maryland"}},
    {"onestop_id":"f-c215-gorgewet~wa~us","tags":{"feed_id": "gorgewet-wa-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dqb0q-charlottesvilleareatransit","tags":{"gtfs_data_exchange": "charlottesville-transit-service"}},
    {"onestop_id":"f-dnxs-gltc~lynchburg~va~us","tags":{"feed_id": "gltc-lynchburg-va-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9vxz-jatran~ms~us","tags":{"feed_id": "jatran-ms-us", "managed_by": "trillium", "gtfs_data_exchange": "jatran"}},
    {"onestop_id":"f-dp8d-jts~wi~us","tags":{"feed_id": "jts-wi-us", "managed_by": "trillium", "gtfs_data_exchange": "janesville-transit-system"}},
    {"onestop_id":"f-9r92-basin~or~us","tags":{"feed_id": "basin-or-us", "managed_by": "trillium", "gtfs_data_exchange": "basin-transit-service"}},
    {"onestop_id":"f-9r1-tehama~ca~us","tags":{"feed_id": "tehama-ca-us", "managed_by": "trillium", "gtfs_data_exchange": " Susanville Indian Rancheria Public Transportation Program"}},
    {"onestop_id":"f-dp1b-terrehautetransit~in~us","tags":{"feed_id": "terrehautetransit-in-us", "managed_by": "trillium", "gtfs_data_exchange": "terre-haute-transit"}},
    {"onestop_id":"f-9mu-orangecountytransportationauthority","tags":{"demo_feed": "true", "gtfs_data_exchange": "orange-county-transportation-authority"}},
    {"onestop_id":"f-f24-octranspo","tags":{"gtfs_data_exchange": "oc-transpo"}},
    {"onestop_id":"f-spv-lignesdazur","tags":{"gtfs_data_exchange": "lignes-dazur"}},
    {"onestop_id":"f-9r4-lassen~ca~us","tags":{"feed_id": "lassen-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "lassen-rural-bus"}},
    {"onestop_id":"f-c20f-cccxpress~or~us","tags":{"feed_id": "cccxpress-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9px-cooscounty~or~us","tags":{"feed_id": "cooscounty-or-us", "managed_by": "trillium", "gtfs_data_exchange": "coos-county-area-transit"}},
    {"onestop_id":"f-dpq-lakecounty~oh~us","tags":{"feed_id": "lakecounty-oh-us"}},
    {"onestop_id":"f-9r8-josephinecounty~or~us","tags":{"feed_id": "josephinecounty-or-us", "managed_by": "trillium", "gtfs_data_exchange": "o-9r8-josephinecommunitytransit"}},
    {"onestop_id":"f-9pz-lincolncounty~or~us","tags":{"feed_id": "lincolncounty-or-us", "managed_by": "trillium", "gtfs_data_exchange": "lincoln-county-transit"}},
    {"onestop_id":"f-9rc-cobreeze~or~us","tags":{"feed_id": "cobreeze-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9rbm-corvallis~or~us","tags":{"feed_id": "corvallis-or-us", "managed_by": "trillium", "gtfs_data_exchange": "corvallis-transit-system"}},
    {"onestop_id":"f-c20-tillamook~or~us","tags":{"feed_id": "tillamook-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c20c-sctd~or~us","tags":{"feed_id": "sctd-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c20dz-washingtonparkshuttle~or~us","tags":{"feed_id": "washingtonparkshuttle-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c208u-woodburn~or~us","tags":{"feed_id": "woodburn-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c20-yamhillcounty~or~us","tags":{"feed_id": "yamhillcounty-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9x8-pocatelloregionaltransit","tags":{"gtfs_data_exchange": "pocatello-regional-transit"}},
    {"onestop_id":"f-dqcjj-arlingtontransit","tags":{"gtfs_data_exchange": "arlington-transit"}},
    {"onestop_id":"f-djq-sunshinebuscompany~fl~us","tags":{"feed_id": "sunshinebuscompany-fl-us", "managed_by": "trillium", "gtfs_data_exchange": "sunshine-bus-company"}},
    {"onestop_id":"f-dhv-psta","tags":{"gtfs_data_exchange": "psta"}},
    {"onestop_id":"f-dnpz-fast","tags":{"status": "unpublished"}},
    {"onestop_id":"f-dr4e-patco","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-drm-blockislandferry~ri~us","tags":{"feed_id": "blockislandferry-ri-us"}},
    {"onestop_id":"f-dpc8-sheboygan~wi~us","tags":{"feed_id": "sheboygan-wi-us"}},
    {"onestop_id":"f-dpmg-rta","tags":{"gtfs_data_exchange": "greater-cleveland-regional-transit-authority"}},
    {"onestop_id":"f-c25-ctuir~or~us","tags":{"feed_id": "ctuir-or-us", "managed_by": "trillium", "gtfs_data_exchange": "kayak-public-transit"}},
    {"onestop_id":"f-9qh-riversidetransitagency","tags":{"gtfs_data_exchange": "riverside-transit-agency"}},
    {"onestop_id":"f-9xj-rtd","tags":{"gtfs_data_exchange": "regional-transportation-district"}},
    {"onestop_id":"f-rtddenver~rt","tags":{"notes": "Needs HTTP Basic Auth."}},
    {"onestop_id":"f-9vg3-startransit~tx~us","tags":{"feed_id": "startransit-tx-us", "managed_by": "trillium"}},
    {"onestop_id":"f-dr7-nywaterway","tags":{"gtfs_data_exchange": "ny-waterway"}},
    {"onestop_id":"f-djj2-pascocountypublictransit~fl~us","tags":{"feed_id": "pascocountypublictransit-fl-us"}},
    {"onestop_id":"f-dr8-rochester~geneseeregionaltransportationauthority","tags":{"gtfs_data_exchange": "rochester-genesee-regional-transportation-authority"}},
    {"onestop_id":"f-9q9-scmtdcom","tags":{"gtfs_data_exchange": "santa-cruz-metro"}},
    {"onestop_id":"f-dru-chittendoncounty~vt~us","tags":{"feed_id": "chittendoncounty-vt-us", "managed_by": "trillium"}},
    {"onestop_id":"f-f25e-societedetransportdelaval","tags":{"gtfs_data_exchange": "societe-de-transport-de-laval"}},
    {"onestop_id":"f-s-societàtrasportipubblicibrindisi","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9qj-sunlinetransitagency","tags":{"gtfs_data_exchange": "sunline-transit-agency"}},
    {"onestop_id":"f-dngy-transitauthorityofnorthernkentucky","tags":{"gtfs_data_exchange": "transit-authority-of-northern-kentucky"}},
    {"onestop_id":"f-dps2-annarborareatransportationauthority","tags":{"gtfs_data_exchange": "ann-arbor-area-transportation-authority"}},
    {"onestop_id":"f-dhvk-manatee~fl~us","tags":{"feed_id": "manatee-fl-us", "managed_by": "trillium", "gtfs_data_exchange": "manatee-county-area-transit"}},
    {"onestop_id":"f-d-groometransportation~us","tags":{"feed_id": "groometransportation-us"}},
    {"onestop_id":"f-drmm-southeasternregionaltransitauthority","tags":{"managed_by": "trillium", "gtfs_data_exchange": "southeastern-regional-transit-authority"}},
    {"onestop_id":"f-ez66z-tuvr~urbanosdevilareal","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-dnrug-duke~nc~us","tags":{"feed_id": "duke-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-u3-günterangergüterverkehrsgmbh~coomnibusvermietungkg~fritzbeh","tags":{"manual_import": "true"}},
    {"onestop_id":"f-dnx-roanoke~va~us","tags":{"feed_id": "roanoke-va-us", "gtfs_data_exchange": "radar-transit"}},
    {"onestop_id":"f-f259-citduhaut~saint~laurent","tags":{"gtfs_data_exchange": "cit-du-haut-saint-laurent"}},
    {"onestop_id":"f-f25d-citlerichelain","tags":{"gtfs_data_exchange": "cit-le-richelain"}},
    {"onestop_id":"f-9rb-eugenetocoosbay~or~us","tags":{"feed_id": "eugenetocoosbay-or-us", "managed_by": "trillium", "gtfs_data_exchange": "eugene-to-coos-bay"}},
    {"onestop_id":"f-f25-citsorel~varennes","tags":{"gtfs_data_exchange": "cit-sorel-varennes"}},
    {"onestop_id":"f-drs-truenorthtransit~ma~us","tags":{"status": "unpublished", "feed_id": "truenorthtransit-ma-us", "managed_by": "trillium"}},
    {"onestop_id":"f-c2qft-udash~mt~us","tags":{"feed_id": "udash-mt-us", "managed_by": "trillium", "gtfs_data_exchange": "mountain-line-mutd"}},
    {"onestop_id":"f-djkj-starmetro","tags":{"managed_by": "trillium"}},
    {"onestop_id":"f-c3j-757","tags":{"feed_id": "757"}},
    {"onestop_id":"f-9wgzn-741","tags":{"feed_id": "741"}},
    {"onestop_id":"f-87z-thebus","tags":{"gtfs_data_exchange": "thebus"}},
    {"onestop_id":"f-9q5d-707","tags":{"feed_id": "707"}},
    {"onestop_id":"f-9xh-cme~co~us","tags":{"feed_id": "cme-co-us"}},
    {"onestop_id":"f-9zr0n-759","tags":{"feed_id": "759"}},
    {"onestop_id":"f-9ze3-755","tags":{"feed_id": "755"}},
    {"onestop_id":"f-9zmzj-767","tags":{"feed_id": "767"}},
    {"onestop_id":"f-9q8yy-missionbaytma~ca~us","tags":{"feed_id": "missionbaytma-ca-us"}},
    {"onestop_id":"f-9xj5s-viamobilityservices~co~us","tags":{"feed_id": "viamobilityservices-co-us"}},
    {"onestop_id":"f-dr-coachcompany~ma~us","tags":{"feed_id": "coachcompany-ma-us"}},
    {"onestop_id":"f-9qdd-maderaareaexpress~ca~us","tags":{"feed_id": "maderaareaexpress-ca-us"}},
    {"onestop_id":"f-9q5-dpwlacounty~ca~us","tags":{"feed_id": "dpwlacounty-ca-us"}},
    {"onestop_id":"f-c20-wotm~wa~us","tags":{"feed_id": "wotm-wa-us"}},
    {"onestop_id":"f-drgv-lctferries~vt~us","tags":{"feed_id": "lctferries-vt-us"}},
    {"onestop_id":"f-dn6hr-tma~tn~us","tags":{"feed_id": "tma-tn-us"}},
    {"onestop_id":"f-9wk-sandiashuttle~nm~us","tags":{"feed_id": "sandiashuttle-nm-us"}},
    {"onestop_id":"f-9wv-coloradoshuttle~co~us","tags":{"feed_id": "coloradoshuttle-co-us"}},
    {"onestop_id":"f-9r0-trinity~ca~us","tags":{"feed_id": "trinity-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "trinity-transit"}},
    {"onestop_id":"f-dpc4-oshkosh~wi~us","tags":{"feed_id": "oshkosh-wi-us", "managed_by": "trillium", "gtfs_data_exchange": "go-transit-city-of-oshkosh"}},
    {"onestop_id":"f-9xhv-nps~romo~shuttles","tags":{"schedule_frequencies": "true"}},
    {"onestop_id":"f-dne-bgcap~ky~us","tags":{"feed_id": "bgcap-ky-us"}},
    {"onestop_id":"f-9qc7-unitransdavis","tags":{"gtfs_data_exchange": "unitrans-davis"}},
    {"onestop_id":"f-9v1z-viametropolitantransit","tags":{"gtfs_data_exchange": "via-metropolitan-transit"}},
    {"onestop_id":"f-f-viarail~traindecharlevoix","tags":{"download_page_url": "https://www.viarail.ca/en/developer-resources"}},
    {"onestop_id":"f-drkg-seatbus~ct~us","tags":{"feed_id": "seatbus-ct-us"}},
    {"onestop_id":"f-9q9j-commute~ca~us","tags":{"feed_id": "commute-ca-us"}},
    {"onestop_id":"f-ezw5f-tuvisa~euskotran","tags":{"gtfs_data_exchange": "tuvisa-euskotran"}},
    {"onestop_id":"f-dru8-advancetransit","tags":{"gtfs_data_exchange": "advance-transit"}},
    {"onestop_id":"f-f25f-citchambly~richelieu~carignan","tags":{"gtfs_data_exchange": "cit-chambly-richelieu-carignan"}},
    {"onestop_id":"f-dprp-eriemta~pa~us","tags":{"feed_id": "eriemta-pa-us"}},
    {"onestop_id":"f-9q9-vta","tags":{"demo_feed": "true", "download_page_url": "http://data.vta.org/datasets/5d8737b6593a47a280636679aa337966"}},
    {"onestop_id":"f-f253-citsud~ouest","tags":{"gtfs_data_exchange": "cit-sud-ouest"}},
    {"onestop_id":"f-9qd-madera~ca~us","tags":{"feed_id": "madera-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "o-9qdd7-maderaareaexpress"}},
    {"onestop_id":"f-9rc-highdesertpoint~or~us","tags":{"feed_id": "highdesertpoint-or-us", "managed_by": "trillium", "gtfs_data_exchange": "highdesert-point"}},
    {"onestop_id":"f-rtm~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-9rb-hut~or~us","tags":{"feed_id": "hut-or-us", "managed_by": "trillium", "gtfs_data_exchange": "hut-airport-shuttle"}},
    {"onestop_id":"f-9rb-valleyretriever~or~us","tags":{"feed_id": "valleyretriever-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-f256-mrcdedeux~montagnes","tags":{"gtfs_data_exchange": "mrc-de-deux-montagnes"}},
    {"onestop_id":"f-dnwg-bt4u","tags":{"gtfs_data_exchange": "blacksburg-transit"}},
    {"onestop_id":"f-u0-sncf~tram~train~ter","tags":{"manual_import": "true", "gtfs_data_exchange": "sncf"}},
    {"onestop_id":"f-c26-yakimatransit","tags":{"managed_by": "mjc"}},
    {"onestop_id":"f-u0nkbh2-aziendavaresinatrasporti","tags":{"gtfs_data_exchange": "azienda-varesina-trasporti"}},
    {"onestop_id":"f-9q9p-sanfranciscobayferry","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9q9-caltrain","tags":{"demo_feed": "true", "gtfs_data_exchange": "caltrain"}},
    {"onestop_id":"f-9qc-capitolcorridor","tags":{"managed_by": "mtc-ca"}},
    {"onestop_id":"f-9q9p-countyconnection","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-dp0w-connecttransit~il~us","tags":{"feed_id": "connecttransit-il-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9x0-uta","tags":{"gtfs_data_exchange": "utah-transit-authority"}},
    {"onestop_id":"f-u0p-trenitalia~obb","tags":{"gtfs_data_exchange": "trenitalia"}},
    {"onestop_id":"f-dp1h-champaignurbanamasstransitdistrict","tags":{"gtfs_data_exchange": "champaign-urbana-mass-transit-district"}},
    {"onestop_id":"f-dhw-miamidadetransit","tags":{"gtfs_data_exchange": "miami-dade-transit"}},
    {"onestop_id":"f-dppc-alleganycountytransit","tags":{"gtfs_data_exchange": "allegany-county-transit"}},
    {"onestop_id":"f-drce-kingstontransit","tags":{"gtfs_data_exchange": "kingston-transit"}},
    {"onestop_id":"f-9q8-samtrans","tags":{"demo_feed": "true", "download_page_url": "http://www.samtrans.com/Developer.html"}},
    {"onestop_id":"f-u0sr-lemet~proxis","tags":{"source_webpage": "https://www.data.gouv.fr/fr/datasets/transport-donnees-gtfs/"}},
    {"onestop_id":"f-9qh0-anaheim~ca~us","tags":{"feed_id": "anaheim-ca-us", "demo_feed": "true", "managed_by": "trillium", "gtfs_data_exchange": "anaheim-resort-transportation", "schedule_frequencies": "true"}},
    {"onestop_id":"f-dnm6-asheville~nc~us","tags":{"feed_id": "asheville-nc-us", "managed_by": "trillium"}},
    {"onestop_id":"f-drs-thebus~vt~us","tags":{"feed_id": "thebus-vt-us", "managed_by": "trillium", "gtfs_data_exchange": "the-bus-marble-valley-regional-transit-district"}},
    {"onestop_id":"f-9rb-pacificcrest~or~us","tags":{"feed_id": "pacificcrest-or-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9xhg-winterpark~co~us","tags":{"feed_id": "winterpark-co-us"}},
    {"onestop_id":"f-f257-citlaurentides","tags":{"gtfs_data_exchange": "cit-laurentides"}},
    {"onestop_id":"f-f25u-mrcdelassomption","tags":{"gtfs_data_exchange": "mrc-de-lassomption"}},
    {"onestop_id":"f-eycs0-soflusa","tags":{"source_webpage": "http://www.transporlis.pt/Default.aspx?tabid=254&language=pt-PT&codOp=14"}},
    {"onestop_id":"f-c22-mason~wa~us","tags":{"feed_id": "mason-wa-us", "managed_by": "trillium"}},
    {"onestop_id":"f-9r4-plumas~ca~us","tags":{"feed_id": "plumas-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "plumas-transit"}},
    {"onestop_id":"f-9w-elevatedtransit~ut~us","tags":{"feed_id": "elevatedtransit-ut-us", "managed_by": "trillium", "gtfs_data_exchange": "elevated-transit"}},
    {"onestop_id":"f-piercetransit~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-dngy-southwestohioregionaltransitauthority","tags":{"gtfs_data_exchange": "southwest-ohio-regional-transit-authority"}},
    {"onestop_id":"f-c29-communitytransit","tags":{"gtfs_data_exchange": "community-transit"}},
    {"onestop_id":"f-dpxq-burlingtontransit","tags":{"gtfs_data_exchange": "burlington-transit"}},
    {"onestop_id":"f-u0-openov~lu","tags":{"schedule_frequencies": "true"}},
    {"onestop_id":"f-eyce-fertagus","tags":{"source_webpage": "http://www.transporlis.pt/Default.aspx?tabid=254&language=pt-PT&codOp=13"}},
    {"onestop_id":"f-eyckr-metrodelisboa","tags":{"source_webpage": "http://www.transporlis.pt/Default.aspx?tabid=254&language=pt-PT&codOp=13"}},
    {"onestop_id":"f-9r0-redding~ca~us","tags":{"feed_id": "redding-ca-us", "managed_by": "trillium", "gtfs_data_exchange": "redding-area-bus-authority"}},
    {"onestop_id":"f-9q5-vctc~ca~us","tags":{"feed_id": "vctc-ca-us"}},
    {"onestop_id":"f-9mgve-avalon~ca~us","tags":{"feed_id": "avalon-ca-us"}},
    {"onestop_id":"f-9y7v-metropolitantulsatransitauthority","tags":{"gtfs_data_exchange": "metropolitan-tulsa-transit-authority"}},
    {"onestop_id":"f-f25g-omitsainte~julie","tags":{"gtfs_data_exchange": "omit-sainte-julie"}},
    {"onestop_id":"f-66tm-liserco~lincosur~lisanco","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-sr-atac~romatpl~trenitalia","tags":{"demo_feed": "true"}},
    {"onestop_id":"f-spz-capconsorzioautolineepratesi","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-spzbz-gestspa","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-spzc-ataf~linea","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-spz-vaibus","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-spz-blubus","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-srb-autolineemugellovaldisieve","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-sr8-etruriamobilità","tags":{"source_webpage": "http://dati.toscana.it/dataset/rt-oraritb"}},
    {"onestop_id":"f-sp-trenitaliaspa","tags":{"gtfs_data_exchange": "trenitalia"}},
    {"onestop_id":"f-everetttransit~rt","tags":{"notes": "Requires API key."}},
    {"onestop_id":"f-u2m-bkk","tags":{"gtfs_data_exchange": "bkk"}},
    {"onestop_id":"f-69y7-recursosdatabuenosairesgobar","tags":{"download_page_url": "https://data.buenosaires.gob.ar/dataset/subte-gtfs", "schedule_frequencies": "true"}},
    {"onestop_id":"f-spzb-piùbus","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9q7-getbus","tags":{"gtfs_data_exchange": "golden-empire-transit-district"}},
    {"onestop_id":"f-9z70-lincolnstartran","tags":{"status": "unreachable"}},
    {"onestop_id":"f-6fes-empresapublicadetransportesecirculação","tags":{"unstable_url": "true"}},
    {"onestop_id":"f-9qc3-datatrilliumtransitcom","tags":{"managed_by": "trillium", "gtfs_data_exchange": "rio-vista-delta-breeze"}},
    {"onestop_id":"f-c23p1-seattlechildrenshospitalshuttle","tags":{"gtfs_data_exchange": "seattle-childrens-hospital-shuttle"}},
    {"onestop_id":"f-9q5c-bigbluebus","tags":{"gtfs_data_exchange": "big-blue-bus"}},
    {"onestop_id":"f-dr5r-mtanewyorkcitytransit","tags":{"manual_import": "true"}},
    {"onestop_id":"f-eyck-carris","tags":{"source_webpage": "http://www.transporlis.pt/Default.aspx?tabid=254&language=pt-PT&codOp=1"}},
    {"onestop_id":"f-dhx-tri~rail","tags":{"gtfs_data_exchange": "tri-rail"}},
    {"onestop_id":"f-drmu1-patriotpartyboats~ma~us","tags":{"feed_id": "patriotpartyboats-ma-us", "managed_by": "trillium"}},
    {"onestop_id":"f-f25d-citroussillon","tags":{"gtfs_data_exchange": "cit-roussillon"}},
    {"onestop_id":"f-9q9p3-datatrilliumtransitcom","tags":{"gtfs_data_exchange": "bear-transit-uc-berkeley-shuttle"}},
]

SKIP_TAGS = {"unreachable", "demo_feed", "schedule_frequencies", "download_page_url", "source_webpage"}

ALLTAGS = set()
FEED_TAG_UPDATES = {}
for feed in FEED_TAGS:
    tags2 = {}
    for k,v in feed['tags'].items():
        ALLTAGS.add(k)
        if k in SKIP_TAGS:
            continue
        tags2[k] = v
    if len(tags2) > 0:
        FEED_TAG_UPDATES[feed['onestop_id']] = tags2

      
print("ALLTAGS:", ALLTAGS)

for fn in glob.glob("feeds/*.dmfr.json"):
    d = {}
    with open(fn,  encoding="utf-8") as ff:
        d = json.load(ff)
    
    f2 = []
    updated = False
    for feed in d['feeds']:
        updated_tags = FEED_TAG_UPDATES.get(feed['id'])
        if updated_tags:
            updated = True
            feed['tags'] = updated_tags
            f2.append(feed)
            print("updated feed:", feed)
        else:
            f2.append(feed)
    d['feeds'] = f2

    if updated:
        with open(fn, 'w',  encoding="utf-8") as ff:
            json.dump(d, ff, indent=2, ensure_ascii=False)

