name: Update GBFS
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install pipenv
        cd scripts && pipenv install
    - name: Install transitland-lib
      run: |
        wget https://github.com/interline-io/transitland-lib/releases/download/v0.11.1/transitland-linux -O transitland
        chmod a+rx transitland
        sudo mv transitland /usr/local/bin
    - name: Fetch latest data
      run: |-
        cd scripts && pipenv run python convert-gbfs-csv-to-dmfr.py > ../feeds/nabsa.github.com.dmfr.json
    - name: Format in the opinionated DMFR format
      run: |
        find ./feeds -type f -name "*.dmfr.json" -exec transitland dmfr format --save {} \;
    - name: Validate feeds
      run: cd scripts && python validate-feeds.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated Bot"
        git config user.email "info@interline.io"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated GBFS feeds from https://github.com/NABSA/gbfs/blob/master/systems.csv at ${timestamp}" || exit 0
        git push
