name: Update Spanish NAP feeds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: '3.10'
    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      with:
        cache-dependency-glob: |
          external-data-for-reference/spain/*.py
          scripts/*.py
    - name: Install transitland-lib
      run: scripts/install-transitland-lib.sh
    - name: Fetch latest Spanish NAP data
      working-directory: external-data-for-reference/spain
      run: uv run collect-nap-gtfs.py
      env:
        SPANISH_NAP_API_KEY: ${{ secrets.SPANISH_NAP_API_KEY }}
    - name: Format in the opinionated DMFR format
      run: transitland dmfr format --save feeds/nap.transportes.gob.es.dmfr.json
    - name: Validate feeds
      working-directory: scripts
      run: uv run validate-feeds.py
      env:
        DMFR_SCHEMA_VERSION: v0.6.0
    - name: Open or update auto-PR if anything changed
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        scripts/auto-pr.sh \
          --branch-name "auto/spanish-nap" \
          --pr-title "Automatic update of Spanish NAP feeds" \
          --pr-body "Automatically updated Spanish NAP feeds from nap.transportes.gob.es" \
          --commit-message "Updated Spanish NAP feeds from nap.transportes.gob.es at $(date -u)"

